openapi: 3.1.0
info:
  description: "This API CRUDs SLO objects for the Grafana plugin. \nModifying an\
    \ SLO object will create or update recording and alerting rules in a connected\
    \ Prometheus instance and create or update dashboards in Grafana."
  title: Grafana SLO API
  version: 1.0.0
servers:
- description: API Subpath
  url: /api/plugins/grafana-slo-app/resources
security:
- bearerAuth: []
paths:
  /v1/slo:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.SLOListResponse'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/api.SLOListResponse'
            application/yaml:
              schema:
                $ref: '#/components/schemas/api.SLOListResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
          description: Internal Server Error
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/slo.v0_0.Slo'
          application/x-yaml:
            schema:
              $ref: '#/components/schemas/slo.v0_0.Slo'
          application/yaml:
            schema:
              $ref: '#/components/schemas/slo.v0_0.Slo'
        required: true
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.SLOCreateResponse'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/api.SLOCreateResponse'
            application/yaml:
              schema:
                $ref: '#/components/schemas/api.SLOCreateResponse'
          description: Accepted
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
          description: Internal Server Error
  /v1/slo/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
          description: Internal Server Error
    get:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/slo.v0_0.Slo'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/slo.v0_0.Slo'
            application/yaml:
              schema:
                $ref: '#/components/schemas/slo.v0_0.Slo'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
          description: Internal Server Error
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/slo.v0_0.Slo'
          application/x-yaml:
            schema:
              $ref: '#/components/schemas/slo.v0_0.Slo'
          application/yaml:
            schema:
              $ref: '#/components/schemas/slo.v0_0.Slo'
        required: true
      responses:
        "202":
          description: Accepted
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
            application/yaml:
              schema:
                $ref: '#/components/schemas/api.ErrorResponse'
          description: Internal Server Error
components:
  schemas:
    api.ErrorResponse:
      additionalProperties: false
      example:
        code: 5
        error: error
      properties:
        code:
          format: int64
          type: integer
        error:
          type: string
      required:
      - code
      - error
    api.SLOCreateResponse:
      additionalProperties: false
      example:
        message: message
        uuid: uuid
      properties:
        message:
          type: string
        uuid:
          type: string
      required:
      - message
      - uuid
    api.SLOListResponse:
      additionalProperties: false
      example:
        slos:
        - searchExpression: searchExpression
          folder:
            uid: uid
          query:
            freeform:
              query: query
            failureRatio:
              failureMetric:
                prometheusMetric: prometheusMetric
                type: type
              groupByLabels:
              - groupByLabels
              - groupByLabels
              totalMetric:
                prometheusMetric: prometheusMetric
                type: type
            threshold:
              threshold:
                value: 1.4658129805029452
                operator: <
              thresholdExpression: thresholdExpression
            type: freeform
            ratio:
              successMetric:
                prometheusMetric: prometheusMetric
                type: type
              groupByLabels:
              - groupByLabels
              - groupByLabels
              totalMetric:
                prometheusMetric: prometheusMetric
                type: type
          name: name
          description: description
          objectives:
          - window: window
            value: 6.027456183070403
          - window: window
            value: 6.027456183070403
          readOnly:
            provenance: provenance
            allowedActions:
            - allowedActions
            - allowedActions
            drillDownDashboardRef:
              UID: UID
            status:
              message: message
              type: created
          destinationDatasource:
            uid: uid
            type: type
          uuid: uuid
          alerting:
            advancedOptions:
              minFailures: 0
            annotations:
            - value: value
              key: key
            - value: value
              key: key
            slowBurn:
              annotations:
              - value: value
                key: key
              - value: value
                key: key
              labels:
              - value: value
                key: key
              - value: value
                key: key
            fastBurn:
              annotations:
              - value: value
                key: key
              - value: value
                key: key
              labels:
              - value: value
                key: key
              - value: value
                key: key
            labels:
            - value: value
              key: key
            - value: value
              key: key
          labels:
          - value: value
            key: key
          - value: value
            key: key
        - searchExpression: searchExpression
          folder:
            uid: uid
          query:
            freeform:
              query: query
            failureRatio:
              failureMetric:
                prometheusMetric: prometheusMetric
                type: type
              groupByLabels:
              - groupByLabels
              - groupByLabels
              totalMetric:
                prometheusMetric: prometheusMetric
                type: type
            threshold:
              threshold:
                value: 1.4658129805029452
                operator: <
              thresholdExpression: thresholdExpression
            type: freeform
            ratio:
              successMetric:
                prometheusMetric: prometheusMetric
                type: type
              groupByLabels:
              - groupByLabels
              - groupByLabels
              totalMetric:
                prometheusMetric: prometheusMetric
                type: type
          name: name
          description: description
          objectives:
          - window: window
            value: 6.027456183070403
          - window: window
            value: 6.027456183070403
          readOnly:
            provenance: provenance
            allowedActions:
            - allowedActions
            - allowedActions
            drillDownDashboardRef:
              UID: UID
            status:
              message: message
              type: created
          destinationDatasource:
            uid: uid
            type: type
          uuid: uuid
          alerting:
            advancedOptions:
              minFailures: 0
            annotations:
            - value: value
              key: key
            - value: value
              key: key
            slowBurn:
              annotations:
              - value: value
                key: key
              - value: value
                key: key
              labels:
              - value: value
                key: key
              - value: value
                key: key
            fastBurn:
              annotations:
              - value: value
                key: key
              - value: value
                key: key
              labels:
              - value: value
                key: key
              - value: value
                key: key
            labels:
            - value: value
              key: key
            - value: value
              key: key
          labels:
          - value: value
            key: key
          - value: value
            key: key
      properties:
        slos:
          items:
            $ref: '#/components/schemas/slo.v0_0.Slo'
          type: array
      required:
      - slos
    slo.v0_0.AdvancedOptions:
      additionalProperties: false
      example:
        minFailures: 0
      properties:
        minFailures:
          format: int64
          type: integer
    slo.v0_0.Alerting:
      additionalProperties: false
      example:
        advancedOptions:
          minFailures: 0
        annotations:
        - value: value
          key: key
        - value: value
          key: key
        slowBurn:
          annotations:
          - value: value
            key: key
          - value: value
            key: key
          labels:
          - value: value
            key: key
          - value: value
            key: key
        fastBurn:
          annotations:
          - value: value
            key: key
          - value: value
            key: key
          labels:
          - value: value
            key: key
          - value: value
            key: key
        labels:
        - value: value
          key: key
        - value: value
          key: key
      properties:
        advancedOptions:
          $ref: '#/components/schemas/slo.v0_0.AdvancedOptions'
        annotations:
          items:
            $ref: '#/components/schemas/slo.v0_0.Label'
          type: array
        fastBurn:
          $ref: '#/components/schemas/slo.v0_0.AlertingMetadata'
        labels:
          items:
            $ref: '#/components/schemas/slo.v0_0.Label'
          type: array
        slowBurn:
          $ref: '#/components/schemas/slo.v0_0.AlertingMetadata'
    slo.v0_0.AlertingMetadata:
      additionalProperties: false
      example:
        annotations:
        - value: value
          key: key
        - value: value
          key: key
        labels:
        - value: value
          key: key
        - value: value
          key: key
      properties:
        annotations:
          items:
            $ref: '#/components/schemas/slo.v0_0.Label'
          type: array
        labels:
          items:
            $ref: '#/components/schemas/slo.v0_0.Label'
          type: array
    slo.v0_0.DashboardRef:
      additionalProperties: false
      example:
        UID: UID
      properties:
        UID:
          type: string
      required:
      - UID
    slo.v0_0.DestinationDatasource:
      additionalProperties: false
      example:
        uid: uid
        type: type
      properties:
        type:
          type: string
        uid:
          type: string
    slo.v0_0.FailureRatioQuery:
      additionalProperties: false
      example:
        failureMetric:
          prometheusMetric: prometheusMetric
          type: type
        groupByLabels:
        - groupByLabels
        - groupByLabels
        totalMetric:
          prometheusMetric: prometheusMetric
          type: type
      properties:
        failureMetric:
          $ref: '#/components/schemas/slo.v0_0.MetricDef'
        groupByLabels:
          items:
            type: string
          type: array
        totalMetric:
          $ref: '#/components/schemas/slo.v0_0.MetricDef'
      required:
      - failureMetric
      - totalMetric
    slo.v0_0.Folder:
      additionalProperties: false
      example:
        uid: uid
      properties:
        uid:
          type: string
    slo.v0_0.FreeformQuery:
      additionalProperties: false
      example:
        query: query
      properties:
        query:
          type: string
      required:
      - query
    slo.v0_0.Label:
      additionalProperties: false
      example:
        value: value
        key: key
      properties:
        key:
          type: string
        value:
          type: string
      required:
      - key
      - value
    slo.v0_0.MetricDef:
      additionalProperties: false
      example:
        prometheusMetric: prometheusMetric
        type: type
      properties:
        prometheusMetric:
          type: string
        type:
          type: string
      required:
      - prometheusMetric
    slo.v0_0.Objective:
      additionalProperties: false
      example:
        window: window
        value: 6.027456183070403
      properties:
        value:
          format: double
          type: number
        window:
          type: string
      required:
      - value
      - window
    slo.v0_0.Query:
      additionalProperties: false
      example:
        freeform:
          query: query
        failureRatio:
          failureMetric:
            prometheusMetric: prometheusMetric
            type: type
          groupByLabels:
          - groupByLabels
          - groupByLabels
          totalMetric:
            prometheusMetric: prometheusMetric
            type: type
        threshold:
          threshold:
            value: 1.4658129805029452
            operator: <
          thresholdExpression: thresholdExpression
        type: freeform
        ratio:
          successMetric:
            prometheusMetric: prometheusMetric
            type: type
          groupByLabels:
          - groupByLabels
          - groupByLabels
          totalMetric:
            prometheusMetric: prometheusMetric
            type: type
      properties:
        failureRatio:
          $ref: '#/components/schemas/slo.v0_0.FailureRatioQuery'
        freeform:
          $ref: '#/components/schemas/slo.v0_0.FreeformQuery'
        ratio:
          $ref: '#/components/schemas/slo.v0_0.RatioQuery'
        threshold:
          $ref: '#/components/schemas/slo.v0_0.ThresholdQuery'
        type:
          enum:
          - freeform
          - histogram
          - ratio
          - threshold
          type: string
      required:
      - type
    slo.v0_0.RatioQuery:
      additionalProperties: false
      example:
        successMetric:
          prometheusMetric: prometheusMetric
          type: type
        groupByLabels:
        - groupByLabels
        - groupByLabels
        totalMetric:
          prometheusMetric: prometheusMetric
          type: type
      properties:
        groupByLabels:
          items:
            type: string
          type: array
        successMetric:
          $ref: '#/components/schemas/slo.v0_0.MetricDef'
        totalMetric:
          $ref: '#/components/schemas/slo.v0_0.MetricDef'
      required:
      - successMetric
      - totalMetric
    slo.v0_0.ReadOnly:
      additionalProperties: false
      example:
        provenance: provenance
        allowedActions:
        - allowedActions
        - allowedActions
        drillDownDashboardRef:
          UID: UID
        status:
          message: message
          type: created
      properties:
        allowedActions:
          items:
            type: string
          type: array
        drillDownDashboardRef:
          $ref: '#/components/schemas/slo.v0_0.DashboardRef'
        provenance:
          type: string
        status:
          $ref: '#/components/schemas/slo.v0_0.Status'
    slo.v0_0.Slo:
      additionalProperties: false
      example:
        searchExpression: searchExpression
        folder:
          uid: uid
        query:
          freeform:
            query: query
          failureRatio:
            failureMetric:
              prometheusMetric: prometheusMetric
              type: type
            groupByLabels:
            - groupByLabels
            - groupByLabels
            totalMetric:
              prometheusMetric: prometheusMetric
              type: type
          threshold:
            threshold:
              value: 1.4658129805029452
              operator: <
            thresholdExpression: thresholdExpression
          type: freeform
          ratio:
            successMetric:
              prometheusMetric: prometheusMetric
              type: type
            groupByLabels:
            - groupByLabels
            - groupByLabels
            totalMetric:
              prometheusMetric: prometheusMetric
              type: type
        name: name
        description: description
        objectives:
        - window: window
          value: 6.027456183070403
        - window: window
          value: 6.027456183070403
        readOnly:
          provenance: provenance
          allowedActions:
          - allowedActions
          - allowedActions
          drillDownDashboardRef:
            UID: UID
          status:
            message: message
            type: created
        destinationDatasource:
          uid: uid
          type: type
        uuid: uuid
        alerting:
          advancedOptions:
            minFailures: 0
          annotations:
          - value: value
            key: key
          - value: value
            key: key
          slowBurn:
            annotations:
            - value: value
              key: key
            - value: value
              key: key
            labels:
            - value: value
              key: key
            - value: value
              key: key
          fastBurn:
            annotations:
            - value: value
              key: key
            - value: value
              key: key
            labels:
            - value: value
              key: key
            - value: value
              key: key
          labels:
          - value: value
            key: key
          - value: value
            key: key
        labels:
        - value: value
          key: key
        - value: value
          key: key
      properties:
        alerting:
          $ref: '#/components/schemas/slo.v0_0.Alerting'
        description:
          type: string
        destinationDatasource:
          $ref: '#/components/schemas/slo.v0_0.DestinationDatasource'
        folder:
          $ref: '#/components/schemas/slo.v0_0.Folder'
        labels:
          items:
            $ref: '#/components/schemas/slo.v0_0.Label'
          type: array
        name:
          type: string
        objectives:
          items:
            $ref: '#/components/schemas/slo.v0_0.Objective'
          type: array
        query:
          $ref: '#/components/schemas/slo.v0_0.Query'
        readOnly:
          $ref: '#/components/schemas/slo.v0_0.ReadOnly'
        searchExpression:
          type: string
        uuid:
          type: string
      required:
      - description
      - name
      - objectives
      - query
      - uuid
    slo.v0_0.Status:
      additionalProperties: false
      example:
        message: message
        type: created
      properties:
        message:
          type: string
        type:
          enum:
          - created
          - creating
          - deleting
          - error
          - unknown
          - updated
          - updating
          type: string
      required:
      - type
    slo.v0_0.Threshold:
      additionalProperties: false
      example:
        value: 1.4658129805029452
        operator: <
      properties:
        operator:
          enum:
          - <
          - ==
          - <=
          - '!='
          - '>='
          - '>'
          type: string
        value:
          format: double
          type: number
      required:
      - operator
      - value
    slo.v0_0.ThresholdQuery:
      additionalProperties: false
      example:
        threshold:
          value: 1.4658129805029452
          operator: <
        thresholdExpression: thresholdExpression
      properties:
        threshold:
          $ref: '#/components/schemas/slo.v0_0.Threshold'
        thresholdExpression:
          type: string
      required:
      - threshold
      - thresholdExpression
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
